# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170712_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
